#!/usr/bin/env python3

import argparse
import signal
import sys

from pathlib import Path
from ping import parse_lines, pack_record


def main(argv):
    parser = argparse.ArgumentParser(prog=argv[0])
    parser.add_argument("output",
                        type=Path)
    parser.add_argument("-a", "--append",
                        action="store_true")
    args = parser.parse_args(argv[1:])

    mode = "ab" if args.append else "wb"
    with args.output.open(mode) as f:
        for time, _, latency in parse_lines(sys.stdin):
            print(time, latency)
            f.write(pack_record(time, latency))
            f.flush()


if __name__ == "__main__":
    try:
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
        sys.exit(main(sys.argv))
    except KeyboardInterrupt:
        pass
